// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ubrania_ASP.NET_Nowy.Data;

namespace Ubrania_ASP.NET_Nowy.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new { Id = "7930229a-e0f4-4b9f-9784-2b5ee826060d", ConcurrencyStamp = "e7a7f716-7d5f-41a3-9163-f1465d719c34", Name = "Admin", NormalizedName = "ADMIN" }
                    );
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Ubrania_ASP.NET_Nowy.Models.Agreement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Begin");

                    b.Property<DateTime>("End");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<double>("Pesel");

                    b.Property<string>("Surname")
                        .IsRequired();

                    b.Property<double>("Tel");

                    b.HasKey("Id");

                    b.ToTable("Agreements");
                });

            modelBuilder.Entity("Ubrania_ASP.NET_Nowy.Models.AnnualReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Balance");

                    b.Property<DateTime>("Year");

                    b.HasKey("Id");

                    b.ToTable("AnnualReports");
                });

            modelBuilder.Entity("Ubrania_ASP.NET_Nowy.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("Agreement_Id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("Pesel");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Ubrania_ASP.NET_Nowy.Models.Cloth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Agreement_Id");

                    b.Property<int?>("AnnualReportId");

                    b.Property<string>("Box");

                    b.Property<string>("Colour");

                    b.Property<int?>("DailyReportId");

                    b.Property<string>("Description");

                    b.Property<string>("Mark");

                    b.Property<int?>("MonthlyReportId");

                    b.Property<int>("Price");

                    b.Property<double>("Price_RL");

                    b.Property<string>("Size");

                    b.Property<bool>("Sold");

                    b.Property<DateTime>("SoldDate");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.HasIndex("Agreement_Id");

                    b.HasIndex("AnnualReportId");

                    b.HasIndex("DailyReportId");

                    b.HasIndex("MonthlyReportId");

                    b.ToTable("Clothes");
                });

            modelBuilder.Entity("Ubrania_ASP.NET_Nowy.Models.Colour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NameOf");

                    b.Property<int>("PropertyId");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("Colors");

                    b.HasData(
                        new { Id = 11, NameOf = "Czarny", PropertyId = 1 },
                        new { Id = 1, NameOf = "Biały", PropertyId = 1 },
                        new { Id = 2, NameOf = "Różowy", PropertyId = 1 },
                        new { Id = 3, NameOf = "Czerwony", PropertyId = 1 },
                        new { Id = 4, NameOf = "Pomarańczowy", PropertyId = 1 },
                        new { Id = 5, NameOf = "Brązowy", PropertyId = 1 },
                        new { Id = 6, NameOf = "Żółty", PropertyId = 1 },
                        new { Id = 7, NameOf = "Szary", PropertyId = 1 },
                        new { Id = 8, NameOf = "Zielony", PropertyId = 1 },
                        new { Id = 9, NameOf = "Niebieski", PropertyId = 1 },
                        new { Id = 10, NameOf = "Fioletowy", PropertyId = 1 }
                    );
                });

            modelBuilder.Entity("Ubrania_ASP.NET_Nowy.Models.DailyReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Balance");

                    b.Property<DateTime>("Day");

                    b.HasKey("Id");

                    b.ToTable("DailyReports");
                });

            modelBuilder.Entity("Ubrania_ASP.NET_Nowy.Models.LastnamesList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Lastname");

                    b.HasKey("ID");

                    b.ToTable("LastnamesLists");
                });

            modelBuilder.Entity("Ubrania_ASP.NET_Nowy.Models.Mark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NameOf");

                    b.Property<int>("PropertyId");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("Marks");

                    b.HasData(
                        new { Id = 1, NameOf = "Zara", PropertyId = 1 },
                        new { Id = 2, NameOf = "Hnm", PropertyId = 1 },
                        new { Id = 3, NameOf = "Mohito", PropertyId = 1 }
                    );
                });

            modelBuilder.Entity("Ubrania_ASP.NET_Nowy.Models.MonthlyReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Balance");

                    b.Property<DateTime>("Month");

                    b.HasKey("Id");

                    b.ToTable("MonthlyReports");
                });

            modelBuilder.Entity("Ubrania_ASP.NET_Nowy.Models.NamesList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("NamesLists");

                    b.HasData(
                        new { ID = 1, Name = "Ada" },
                        new { ID = 2, Name = "Adamina" },
                        new { ID = 3, Name = "Adela" },
                        new { ID = 4, Name = "Adelajda" },
                        new { ID = 5, Name = "Adriana" },
                        new { ID = 6, Name = "Adrianna" },
                        new { ID = 7, Name = "Agata" },
                        new { ID = 8, Name = "Agnieszka" },
                        new { ID = 9, Name = "Agrypina" },
                        new { ID = 10, Name = "Afra" },
                        new { ID = 11, Name = "Aida" },
                        new { ID = 12, Name = "Aisza" },
                        new { ID = 13, Name = "Ajna" },
                        new { ID = 14, Name = "Alberta" },
                        new { ID = 15, Name = "Albertyna" },
                        new { ID = 16, Name = "Albina" },
                        new { ID = 17, Name = "Aldona" },
                        new { ID = 18, Name = "Aleksa" },
                        new { ID = 19, Name = "Aleksandra" },
                        new { ID = 20, Name = "Aleksja" },
                        new { ID = 21, Name = "Alfreda" },
                        new { ID = 22, Name = "Alicja" },
                        new { ID = 23, Name = "Alida" },
                        new { ID = 24, Name = "Alina" },
                        new { ID = 25, Name = "Alojza" },
                        new { ID = 26, Name = "Amalia" },
                        new { ID = 27, Name = "Amanda" },
                        new { ID = 28, Name = "Amber" },
                        new { ID = 29, Name = "Amelia" },
                        new { ID = 30, Name = "Amina" },
                        new { ID = 31, Name = "Amira" },
                        new { ID = 32, Name = "Ana" },
                        new { ID = 33, Name = "Anastazja" },
                        new { ID = 34, Name = "Andrea" },
                        new { ID = 35, Name = "Andrzeja" },
                        new { ID = 36, Name = "Andżelika" },
                        new { ID = 37, Name = "Aneta" },
                        new { ID = 38, Name = "Angela" },
                        new { ID = 39, Name = "Angelika" },
                        new { ID = 40, Name = "Angelina" },
                        new { ID = 41, Name = "Aniela" },
                        new { ID = 42, Name = "Anita" },
                        new { ID = 43, Name = "Anna" },
                        new { ID = 44, Name = "Antonina" },
                        new { ID = 45, Name = "Anzelma" },
                        new { ID = 46, Name = "Apollona" },
                        new { ID = 47, Name = "Apollina" },
                        new { ID = 48, Name = "Apolonia" },
                        new { ID = 49, Name = "Arabella" },
                        new { ID = 50, Name = "Ariadna" },
                        new { ID = 51, Name = "Arleta" },
                        new { ID = 52, Name = "Arnolda" },
                        new { ID = 53, Name = "Astryda" },
                        new { ID = 54, Name = "Atena" },
                        new { ID = 55, Name = "Augusta" },
                        new { ID = 56, Name = "Augustyna" },
                        new { ID = 57, Name = "Aurelia" },
                        new { ID = 58, Name = "Aurora" },
                        new { ID = 59, Name = "Babeta" },
                        new { ID = 60, Name = "Balbina" },
                        new { ID = 61, Name = "Barbara" },
                        new { ID = 62, Name = "Bartłomieja" },
                        new { ID = 63, Name = "Beata" },
                        new { ID = 64, Name = "Beatrycja" },
                        new { ID = 65, Name = "Beatrycze" },
                        new { ID = 66, Name = "Beatryksa" },
                        new { ID = 67, Name = "Benedykta" },
                        new { ID = 68, Name = "Beniamina" },
                        new { ID = 69, Name = "Berenika" },
                        new { ID = 70, Name = "Bernarda" },
                        new { ID = 71, Name = "Bernadeta" },
                        new { ID = 72, Name = "Berta" },
                        new { ID = 73, Name = "Betina" },
                        new { ID = 74, Name = "Bianka" },
                        new { ID = 75, Name = "Bibiana" },
                        new { ID = 76, Name = "Blanka" },
                        new { ID = 77, Name = "Błażena" },
                        new { ID = 78, Name = "Bogdana" },
                        new { ID = 79, Name = "Bogna" },
                        new { ID = 80, Name = "Boguchwała" },
                        new { ID = 81, Name = "Bogumiła" },
                        new { ID = 82, Name = "Bogusława" },
                        new { ID = 83, Name = "Bojana" },
                        new { ID = 84, Name = "Bolesława" },
                        new { ID = 85, Name = "Bona" },
                        new { ID = 86, Name = "Bożena" },
                        new { ID = 87, Name = "Bromira" },
                        new { ID = 88, Name = "Bronisława" },
                        new { ID = 89, Name = "Brunhilda" },
                        new { ID = 90, Name = "Brygida" },
                        new { ID = 91, Name = "Cecylia" },
                        new { ID = 92, Name = "Celestyna" },
                        new { ID = 93, Name = "Celina" },
                        new { ID = 94, Name = "Cezaria" },
                        new { ID = 95, Name = "Cezaryna" },
                        new { ID = 96, Name = "Chociemira" },
                        new { ID = 97, Name = "Chwalisława" },
                        new { ID = 98, Name = "Ciechosława" },
                        new { ID = 99, Name = "Ciesława" },
                        new { ID = 100, Name = "Cinosława" },
                        new { ID = 101, Name = "Cina" },
                        new { ID = 102, Name = "Czesława" },
                        new { ID = 103, Name = "Dajmira" },
                        new { ID = 104, Name = "Dagna" },
                        new { ID = 105, Name = "Dagmara" },
                        new { ID = 106, Name = "Dalia" },
                        new { ID = 107, Name = "Dalila" },
                        new { ID = 108, Name = "Dalmira" },
                        new { ID = 109, Name = "Damroka" },
                        new { ID = 110, Name = "Dana" },
                        new { ID = 111, Name = "Daniela" },
                        new { ID = 112, Name = "Danisława" },
                        new { ID = 113, Name = "Danuta" },
                        new { ID = 114, Name = "Dargomira" },
                        new { ID = 115, Name = "Dargosława" },
                        new { ID = 116, Name = "Daria" },
                        new { ID = 117, Name = "Dąbrówka" },
                        new { ID = 118, Name = "Delfina" },
                        new { ID = 119, Name = "Delia" },
                        new { ID = 120, Name = "Diana" },
                        new { ID = 121, Name = "Dilara" },
                        new { ID = 122, Name = "Dobiesława" },
                        new { ID = 123, Name = "Domasława" },
                        new { ID = 124, Name = "Dominika" },
                        new { ID = 125, Name = "Donata" },
                        new { ID = 126, Name = "Dorosława" },
                        new { ID = 127, Name = "Dorota" },
                        new { ID = 128, Name = "Dyzma" },
                        new { ID = 129, Name = "Dżanan" },
                        new { ID = 130, Name = "Dżamila" },
                        new { ID = 131, Name = "Dżesika" },
                        new { ID = 132, Name = "Edeltruda" },
                        new { ID = 133, Name = "Edyta" },
                        new { ID = 134, Name = "Eleonora" },
                        new { ID = 135, Name = "Eliza" },
                        new { ID = 136, Name = "Elwira" },
                        new { ID = 137, Name = "Elżbieta" },
                        new { ID = 138, Name = "Elmira" },
                        new { ID = 139, Name = "Emanuela" },
                        new { ID = 140, Name = "Emilia" },
                        new { ID = 141, Name = "Emina" },
                        new { ID = 142, Name = "Emma" },
                        new { ID = 143, Name = "Ernesta" },
                        new { ID = 144, Name = "Ernestyna" },
                        new { ID = 145, Name = "Eryka" },
                        new { ID = 146, Name = "Estera" },
                        new { ID = 147, Name = "Eugenia" },
                        new { ID = 148, Name = "Ewa" },
                        new { ID = 149, Name = "Ewelina" },
                        new { ID = 150, Name = "Fabia" },
                        new { ID = 151, Name = "Fabiana" },
                        new { ID = 152, Name = "Fabiola" },
                        new { ID = 153, Name = "Farida" },
                        new { ID = 154, Name = "Fatima" },
                        new { ID = 155, Name = "Fatma" },
                        new { ID = 156, Name = "Faustyna" },
                        new { ID = 157, Name = "Felicja" },
                        new { ID = 158, Name = "Felicjana" },
                        new { ID = 159, Name = "Felicyta" },
                        new { ID = 160, Name = "Feliksa" },
                        new { ID = 161, Name = "Ferdynanda" },
                        new { ID = 162, Name = "Filipa" },
                        new { ID = 163, Name = "Filipina" },
                        new { ID = 164, Name = "Flora" },
                        new { ID = 165, Name = "Florentyna" },
                        new { ID = 166, Name = "Floriana" },
                        new { ID = 167, Name = "Franciszka" },
                        new { ID = 168, Name = "Fryderyka" },
                        new { ID = 169, Name = "Gabriela" },
                        new { ID = 170, Name = "Gaja" },
                        new { ID = 171, Name = "Genowefa" },
                        new { ID = 172, Name = "Gerarda" },
                        new { ID = 173, Name = "Gertruda" },
                        new { ID = 174, Name = "Gizela" },
                        new { ID = 175, Name = "Gloria" },
                        new { ID = 176, Name = "Gniewomira" },
                        new { ID = 177, Name = "Gracja" },
                        new { ID = 178, Name = "Gracjana" },
                        new { ID = 179, Name = "Grażyna" },
                        new { ID = 180, Name = "Greta" },
                        new { ID = 181, Name = "Gryzelda" },
                        new { ID = 182, Name = "Grzymisława" },
                        new { ID = 183, Name = "Gustawa" },
                        new { ID = 184, Name = "Gwidona" },
                        new { ID = 185, Name = "Hadriana" },
                        new { ID = 186, Name = "Halina" },
                        new { ID = 187, Name = "Halszka" },
                        new { ID = 188, Name = "Hanna" },
                        new { ID = 189, Name = "Hedwiga" },
                        new { ID = 190, Name = "Helena" },
                        new { ID = 191, Name = "Helga" },
                        new { ID = 192, Name = "Henrieta" },
                        new { ID = 193, Name = "Henryka" },
                        new { ID = 194, Name = "Herma" },
                        new { ID = 195, Name = "Hermana" },
                        new { ID = 196, Name = "Hermenegilda" },
                        new { ID = 197, Name = "Hermina" },
                        new { ID = 198, Name = "Hestia" },
                        new { ID = 199, Name = "Hiacynta" },
                        new { ID = 200, Name = "Hilaria" },
                        new { ID = 201, Name = "Hildegarda" },
                        new { ID = 202, Name = "Hipolit" },
                        new { ID = 203, Name = "Honorata" },
                        new { ID = 204, Name = "Hortensja" },
                        new { ID = 205, Name = "Huberta" },
                        new { ID = 206, Name = "Husaria" },
                        new { ID = 207, Name = "Ida" },
                        new { ID = 208, Name = "Idosława" },
                        new { ID = 209, Name = "Idzia" },
                        new { ID = 210, Name = "Idalia" },
                        new { ID = 211, Name = "Idzisława" },
                        new { ID = 212, Name = "Iga" },
                        new { ID = 213, Name = "Ildefonsa" },
                        new { ID = 214, Name = "Ilia" },
                        new { ID = 215, Name = "Iliana" },
                        new { ID = 216, Name = "Ilona" },
                        new { ID = 217, Name = "Ilza" },
                        new { ID = 218, Name = "Inga" },
                        new { ID = 219, Name = "Ingeborga" },
                        new { ID = 220, Name = "Ingryda" },
                        new { ID = 221, Name = "Irena" },
                        new { ID = 222, Name = "Iryda" },
                        new { ID = 223, Name = "Iwa" },
                        new { ID = 224, Name = "Iwona" },
                        new { ID = 225, Name = "Izabela" },
                        new { ID = 226, Name = "Izolda" },
                        new { ID = 227, Name = "Izydora" },
                        new { ID = 228, Name = "Jadwiga" },
                        new { ID = 229, Name = "Jago" },
                        new { ID = 230, Name = "Jana" },
                        new { ID = 231, Name = "Janina" },
                        new { ID = 232, Name = "Jarmiła" },
                        new { ID = 233, Name = "Jaromiła" },
                        new { ID = 234, Name = "Jaromira" },
                        new { ID = 235, Name = "Jarosława" },
                        new { ID = 236, Name = "Jasława" },
                        new { ID = 237, Name = "Jaśmina" },
                        new { ID = 238, Name = "Joachima" },
                        new { ID = 239, Name = "Joanna" },
                        new { ID = 240, Name = "Jolanta" },
                        new { ID = 241, Name = "Jowita" },
                        new { ID = 242, Name = "Józefa" },
                        new { ID = 243, Name = "Józefina" },
                        new { ID = 244, Name = "Judyta" },
                        new { ID = 245, Name = "Julia" },
                        new { ID = 246, Name = "Julianna" },
                        new { ID = 247, Name = "Julisława" },
                        new { ID = 248, Name = "Julita" },
                        new { ID = 249, Name = "Justyna" },
                        new { ID = 250, Name = "Juta" },
                        new { ID = 251, Name = "Kaja" },
                        new { ID = 252, Name = "Kalina" },
                        new { ID = 253, Name = "Kamila" },
                        new { ID = 254, Name = "Karima" },
                        new { ID = 255, Name = "Karina" },
                        new { ID = 256, Name = "Karola" },
                        new { ID = 257, Name = "Karolina" },
                        new { ID = 258, Name = "Karyna" },
                        new { ID = 259, Name = "Katarzyna" },
                        new { ID = 260, Name = "Kasandra" },
                        new { ID = 261, Name = "Kazimiera" },
                        new { ID = 262, Name = "Kiara" },
                        new { ID = 263, Name = "Kiliana" },
                        new { ID = 264, Name = "Kinga" },
                        new { ID = 265, Name = "Kira" },
                        new { ID = 266, Name = "Klara" },
                        new { ID = 267, Name = "Klarysa" },
                        new { ID = 268, Name = "Klaudia" },
                        new { ID = 269, Name = "Klaudyna" },
                        new { ID = 270, Name = "Klementyna" },
                        new { ID = 271, Name = "Kleopatra" },
                        new { ID = 272, Name = "Klotylda" },
                        new { ID = 273, Name = "Konstancja" },
                        new { ID = 274, Name = "Kordula" },
                        new { ID = 275, Name = "Kornelia" },
                        new { ID = 276, Name = "Koryna" },
                        new { ID = 277, Name = "Krystiana" },
                        new { ID = 278, Name = "Krystyna" },
                        new { ID = 279, Name = "Krzysztofa" },
                        new { ID = 280, Name = "Ksawera" },
                        new { ID = 281, Name = "Ksenia" },
                        new { ID = 282, Name = "Kunegunda" },
                        new { ID = 283, Name = "Kwiatosława" },
                        new { ID = 284, Name = "Kwietosława" },
                        new { ID = 285, Name = "Laila" },
                        new { ID = 286, Name = "Lajla" },
                        new { ID = 287, Name = "Lana" },
                        new { ID = 288, Name = "Larisa" },
                        new { ID = 289, Name = "Larysa" },
                        new { ID = 290, Name = "Latifa" },
                        new { ID = 291, Name = "Laura" },
                        new { ID = 292, Name = "Laurenjca" },
                        new { ID = 293, Name = "Lea" },
                        new { ID = 294, Name = "Lejla" },
                        new { ID = 295, Name = "Lena" },
                        new { ID = 296, Name = "Leokadia" },
                        new { ID = 297, Name = "Leona" },
                        new { ID = 298, Name = "Leonarda" },
                        new { ID = 299, Name = "Leoncja" },
                        new { ID = 300, Name = "Leonora" },
                        new { ID = 301, Name = "Leopolda" },
                        new { ID = 302, Name = "Lidia" },
                        new { ID = 303, Name = "Ligia" },
                        new { ID = 304, Name = "Lilia" },
                        new { ID = 305, Name = "Liliana" },
                        new { ID = 306, Name = "Linda" },
                        new { ID = 307, Name = "Liwia" },
                        new { ID = 308, Name = "Lora" },
                        new { ID = 309, Name = "Luborada" },
                        new { ID = 310, Name = "Lucjana" },
                        new { ID = 311, Name = "Lucjola" },
                        new { ID = 312, Name = "Lucyna" },
                        new { ID = 313, Name = "Ludmiła" },
                        new { ID = 314, Name = "Ludolfa" },
                        new { ID = 315, Name = "Ludwika" },
                        new { ID = 316, Name = "Ludwina" },
                        new { ID = 317, Name = "Luiza" },
                        new { ID = 318, Name = "Luna" },
                        new { ID = 319, Name = "Lilianna" },
                        new { ID = 320, Name = "Ładana" },
                        new { ID = 321, Name = "Ładysława" },
                        new { ID = 322, Name = "Łagoda" },
                        new { ID = 323, Name = "Łucja" },
                        new { ID = 324, Name = "Macieja" },
                        new { ID = 325, Name = "Magda" },
                        new { ID = 326, Name = "Magdalena" },
                        new { ID = 327, Name = "Maja" },
                        new { ID = 328, Name = "Maksa" },
                        new { ID = 329, Name = "Maksyma" },
                        new { ID = 330, Name = "Malina" },
                        new { ID = 331, Name = "Malwina" },
                        new { ID = 332, Name = "Małgorzata" },
                        new { ID = 333, Name = "Manuela" },
                        new { ID = 334, Name = "Marcela" },
                        new { ID = 335, Name = "Marcelina" },
                        new { ID = 336, Name = "Marcjana" },
                        new { ID = 337, Name = "Marcjanna" },
                        new { ID = 338, Name = "Maria" },
                        new { ID = 339, Name = "Mariam" },
                        new { ID = 340, Name = "Marianna" },
                        new { ID = 341, Name = "Marietta" },
                        new { ID = 342, Name = "Marika" },
                        new { ID = 343, Name = "Mariola" },
                        new { ID = 344, Name = "Marlena" },
                        new { ID = 345, Name = "Marta" },
                        new { ID = 346, Name = "Martyna" },
                        new { ID = 347, Name = "Maryja" },
                        new { ID = 348, Name = "Maryla" },
                        new { ID = 349, Name = "Maryna" },
                        new { ID = 350, Name = "Marzena" },
                        new { ID = 351, Name = "Matylda" },
                        new { ID = 352, Name = "Melania" },
                        new { ID = 353, Name = "Michalina" },
                        new { ID = 354, Name = "Mieczysława" },
                        new { ID = 355, Name = "Milena" },
                        new { ID = 356, Name = "Milomira" },
                        new { ID = 357, Name = "Miłosława" },
                        new { ID = 358, Name = "Miłowita" },
                        new { ID = 359, Name = "Minerwa" },
                        new { ID = 360, Name = "Mina" },
                        new { ID = 361, Name = "Mira" },
                        new { ID = 362, Name = "Mirabela" },
                        new { ID = 363, Name = "Miranda" },
                        new { ID = 364, Name = "Mirela" },
                        new { ID = 365, Name = "Miriam" },
                        new { ID = 366, Name = "Mirka" },
                        new { ID = 367, Name = "Miroda" },
                        new { ID = 368, Name = "Mirołada" },
                        new { ID = 369, Name = "Mirosława" },
                        new { ID = 370, Name = "Mojmira" },
                        new { ID = 371, Name = "Monika" },
                        new { ID = 372, Name = "Morzana" },
                        new { ID = 373, Name = "Morzena" },
                        new { ID = 374, Name = "Nadia" },
                        new { ID = 375, Name = "Nadzieja" },
                        new { ID = 376, Name = "Najmiła" },
                        new { ID = 377, Name = "Najsława" },
                        new { ID = 378, Name = "Narcyza" },
                        new { ID = 379, Name = "Natalia" },
                        new { ID = 380, Name = "Natasza" },
                        new { ID = 381, Name = "Nela" },
                        new { ID = 382, Name = "Nika" },
                        new { ID = 383, Name = "Nikodema" },
                        new { ID = 384, Name = "Nikola" },
                        new { ID = 385, Name = "Nikita" },
                        new { ID = 386, Name = "Nikoleta" },
                        new { ID = 387, Name = "Nina" },
                        new { ID = 388, Name = "Noemi" },
                        new { ID = 389, Name = "Nora" },
                        new { ID = 390, Name = "Norberta" },
                        new { ID = 391, Name = "Norma" },
                        new { ID = 392, Name = "Oda" },
                        new { ID = 393, Name = "Odeta" },
                        new { ID = 394, Name = "Odyla" },
                        new { ID = 395, Name = "Ofelia" },
                        new { ID = 396, Name = "Oksana" },
                        new { ID = 397, Name = "Oktawia" },
                        new { ID = 398, Name = "Ola" },
                        new { ID = 399, Name = "Olga" },
                        new { ID = 400, Name = "Olimpia" },
                        new { ID = 401, Name = "Oliwia" },
                        new { ID = 402, Name = "Oriana" },
                        new { ID = 403, Name = "Ota" },
                        new { ID = 404, Name = "Otylia" },
                        new { ID = 405, Name = "Ożanna" },
                        new { ID = 406, Name = "Olena" },
                        new { ID = 407, Name = "Pabiana" },
                        new { ID = 408, Name = "Pamela" },
                        new { ID = 409, Name = "Patrycja" },
                        new { ID = 410, Name = "Paula" },
                        new { ID = 411, Name = "Paulina" },
                        new { ID = 412, Name = "Pelagia" },
                        new { ID = 413, Name = "Petra" },
                        new { ID = 414, Name = "Petronela" },
                        new { ID = 415, Name = "Petronia" },
                        new { ID = 416, Name = "Placyda" },
                        new { ID = 417, Name = "Pola" },
                        new { ID = 418, Name = "Polmira" },
                        new { ID = 419, Name = "Przemysława" },
                        new { ID = 420, Name = "Przybysława" },
                        new { ID = 421, Name = "Rachela" },
                        new { ID = 422, Name = "Ramona" },
                        new { ID = 423, Name = "Radmiła" },
                        new { ID = 424, Name = "Radomiła" },
                        new { ID = 425, Name = "Radomira" },
                        new { ID = 426, Name = "Radosława" },
                        new { ID = 427, Name = "Rafaela" },
                        new { ID = 428, Name = "Rajmunda" },
                        new { ID = 429, Name = "Rajna" },
                        new { ID = 430, Name = "Raszyda" },
                        new { ID = 431, Name = "Rebeka" },
                        new { ID = 432, Name = "Regina" },
                        new { ID = 433, Name = "Remigia" },
                        new { ID = 434, Name = "Renata" },
                        new { ID = 435, Name = "Rita" },
                        new { ID = 436, Name = "Roberta" },
                        new { ID = 437, Name = "Rodzisława" },
                        new { ID = 438, Name = "Roksana" },
                        new { ID = 439, Name = "Roma" },
                        new { ID = 440, Name = "Romana" },
                        new { ID = 441, Name = "Romualda" },
                        new { ID = 442, Name = "Rozalia" },
                        new { ID = 443, Name = "Rozalinda" },
                        new { ID = 444, Name = "Rozamunda" },
                        new { ID = 445, Name = "Rozetta" },
                        new { ID = 446, Name = "Rozwita" },
                        new { ID = 447, Name = "Róża" },
                        new { ID = 448, Name = "Rudolfina" },
                        new { ID = 449, Name = "Ruta" },
                        new { ID = 450, Name = "Ryszarda" },
                        new { ID = 451, Name = "Sabina" },
                        new { ID = 452, Name = "Safira" },
                        new { ID = 453, Name = "Salma" },
                        new { ID = 454, Name = "Saloma" },
                        new { ID = 455, Name = "Salomea" },
                        new { ID = 456, Name = "Samanta" },
                        new { ID = 457, Name = "Sandra" },
                        new { ID = 458, Name = "Sara" },
                        new { ID = 459, Name = "Sebastiana" },
                        new { ID = 460, Name = "Selena" },
                        new { ID = 461, Name = "Selma" },
                        new { ID = 462, Name = "Serafina" },
                        new { ID = 463, Name = "Seweryna" },
                        new { ID = 464, Name = "Sędomira" },
                        new { ID = 465, Name = "Sędzisława" },
                        new { ID = 466, Name = "Sława" },
                        new { ID = 467, Name = "Sławina" },
                        new { ID = 468, Name = "Sławomira" },
                        new { ID = 469, Name = "Sobiesława" },
                        new { ID = 470, Name = "Sonia" },
                        new { ID = 471, Name = "Stamira" },
                        new { ID = 472, Name = "Stanisława" },
                        new { ID = 473, Name = "Stefania" },
                        new { ID = 474, Name = "Stela" },
                        new { ID = 475, Name = "Stoisława" },
                        new { ID = 476, Name = "Stella" },
                        new { ID = 477, Name = "Sydney" },
                        new { ID = 478, Name = "Strzeżymira" },
                        new { ID = 479, Name = "Subisława" },
                        new { ID = 480, Name = "Sulima" },
                        new { ID = 481, Name = "Sulisława" },
                        new { ID = 482, Name = "Sybilla" },
                        new { ID = 483, Name = "Sylwana" },
                        new { ID = 484, Name = "Sylwia" },
                        new { ID = 485, Name = "Szarlota" },
                        new { ID = 486, Name = "Szarlin" },
                        new { ID = 487, Name = "Szarlina" },
                        new { ID = 488, Name = "Szejma" },
                        new { ID = 489, Name = "Szymona" },
                        new { ID = 490, Name = "Świetlana" },
                        new { ID = 491, Name = "Świętomira" },
                        new { ID = 492, Name = "Świętosława" },
                        new { ID = 493, Name = "Tabita" },
                        new { ID = 494, Name = "Tacjana" },
                        new { ID = 495, Name = "Tadea" },
                        new { ID = 496, Name = "Tamara" },
                        new { ID = 497, Name = "Tatiana" },
                        new { ID = 498, Name = "Tekla" },
                        new { ID = 499, Name = "Telimena" },
                        new { ID = 500, Name = "Teodora" },
                        new { ID = 501, Name = "Teodozja" },
                        new { ID = 502, Name = "Teresa" },
                        new { ID = 503, Name = "Tęgomira" },
                        new { ID = 504, Name = "Tina" },
                        new { ID = 505, Name = "Tolisława" },
                        new { ID = 506, Name = "Tomiła" },
                        new { ID = 507, Name = "Tomisława" },
                        new { ID = 508, Name = "Tulimira" },
                        new { ID = 509, Name = "Tessa" },
                        new { ID = 510, Name = "Ulana" },
                        new { ID = 511, Name = "Ulryka" },
                        new { ID = 512, Name = "Uma" },
                        new { ID = 513, Name = "Una" },
                        new { ID = 514, Name = "Unima" },
                        new { ID = 515, Name = "Urszula" },
                        new { ID = 516, Name = "Uta" },
                        new { ID = 517, Name = "Wacława" },
                        new { ID = 518, Name = "Walentyna" },
                        new { ID = 519, Name = "Waleria" },
                        new { ID = 520, Name = "Wanda" },
                        new { ID = 521, Name = "Wanessa" },
                        new { ID = 522, Name = "Wera" },
                        new { ID = 523, Name = "Weronika" },
                        new { ID = 524, Name = "Wesna" },
                        new { ID = 525, Name = "Wiara" },
                        new { ID = 526, Name = "Wielina" },
                        new { ID = 527, Name = "Wiera" },
                        new { ID = 528, Name = "Wierada" },
                        new { ID = 529, Name = "Wiesława" },
                        new { ID = 530, Name = "Wiktoria" },
                        new { ID = 531, Name = "Wilhelmina" },
                        new { ID = 532, Name = "Wilma" },
                        new { ID = 533, Name = "Wincentyna" },
                        new { ID = 534, Name = "Wioleta" },
                        new { ID = 535, Name = "Wirgilia" },
                        new { ID = 536, Name = "Wirginia" },
                        new { ID = 537, Name = "Wisława" },
                        new { ID = 538, Name = "Witosława" },
                        new { ID = 539, Name = "Władysława" },
                        new { ID = 540, Name = "Włodzimiera" },
                        new { ID = 541, Name = "Wolimira" },
                        new { ID = 542, Name = "Wrocisława" },
                        new { ID = 543, Name = "Zaida" },
                        new { ID = 544, Name = "Zaira" },
                        new { ID = 545, Name = "Zdzisława" },
                        new { ID = 546, Name = "Zefiryna" },
                        new { ID = 547, Name = "Zenobia" },
                        new { ID = 548, Name = "Zenona" },
                        new { ID = 549, Name = "Zofia" },
                        new { ID = 550, Name = "Zoja" },
                        new { ID = 551, Name = "Zuzanna" },
                        new { ID = 552, Name = "Zwinisława" },
                        new { ID = 553, Name = "Zygfryda" },
                        new { ID = 554, Name = "Zyta" },
                        new { ID = 555, Name = "Żaklina" },
                        new { ID = 556, Name = "Żaneta" },
                        new { ID = 557, Name = "Żanna" },
                        new { ID = 558, Name = "Żelisława" },
                        new { ID = 559, Name = "Żużanna" },
                        new { ID = 560, Name = "Żywia" },
                        new { ID = 561, Name = "Żywisław" }
                    );
                });

            modelBuilder.Entity("Ubrania_ASP.NET_Nowy.Models.NamesOfProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("NamesOfProperties");

                    b.HasData(
                        new { Id = 1 }
                    );
                });

            modelBuilder.Entity("Ubrania_ASP.NET_Nowy.Models.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NameOf");

                    b.Property<int>("PropertyId");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("Sizes");

                    b.HasData(
                        new { Id = 1, NameOf = "xxs", PropertyId = 1 },
                        new { Id = 2, NameOf = "xs", PropertyId = 1 },
                        new { Id = 3, NameOf = "s", PropertyId = 1 },
                        new { Id = 4, NameOf = "m", PropertyId = 1 },
                        new { Id = 5, NameOf = "l", PropertyId = 1 },
                        new { Id = 6, NameOf = "xl", PropertyId = 1 },
                        new { Id = 7, NameOf = "xxl", PropertyId = 1 },
                        new { Id = 8, NameOf = "36", PropertyId = 1 },
                        new { Id = 9, NameOf = "37", PropertyId = 1 },
                        new { Id = 10, NameOf = "38", PropertyId = 1 },
                        new { Id = 11, NameOf = "39", PropertyId = 1 },
                        new { Id = 12, NameOf = "40", PropertyId = 1 },
                        new { Id = 13, NameOf = "41", PropertyId = 1 }
                    );
                });

            modelBuilder.Entity("Ubrania_ASP.NET_Nowy.Models.Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NameOf");

                    b.Property<int>("PropertyId");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("Types");

                    b.HasData(
                        new { Id = 1, NameOf = "Biżuteria", PropertyId = 1 },
                        new { Id = 2, NameOf = "Dodatki", PropertyId = 1 },
                        new { Id = 3, NameOf = "Torebka", PropertyId = 1 },
                        new { Id = 4, NameOf = "Spodnie", PropertyId = 1 },
                        new { Id = 5, NameOf = "Sukienka", PropertyId = 1 },
                        new { Id = 6, NameOf = "Spódnica", PropertyId = 1 },
                        new { Id = 7, NameOf = "Kurtka", PropertyId = 1 },
                        new { Id = 8, NameOf = "Bluzka", PropertyId = 1 },
                        new { Id = 9, NameOf = "Buty", PropertyId = 1 }
                    );
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Ubrania_ASP.NET_Nowy.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Ubrania_ASP.NET_Nowy.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Ubrania_ASP.NET_Nowy.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Ubrania_ASP.NET_Nowy.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ubrania_ASP.NET_Nowy.Models.Cloth", b =>
                {
                    b.HasOne("Ubrania_ASP.NET_Nowy.Models.Agreement", "Agreement")
                        .WithMany("Clothes")
                        .HasForeignKey("Agreement_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Ubrania_ASP.NET_Nowy.Models.AnnualReport")
                        .WithMany("Clothes")
                        .HasForeignKey("AnnualReportId");

                    b.HasOne("Ubrania_ASP.NET_Nowy.Models.DailyReport")
                        .WithMany("Clothes")
                        .HasForeignKey("DailyReportId");

                    b.HasOne("Ubrania_ASP.NET_Nowy.Models.MonthlyReport")
                        .WithMany("Clothes")
                        .HasForeignKey("MonthlyReportId");
                });

            modelBuilder.Entity("Ubrania_ASP.NET_Nowy.Models.Colour", b =>
                {
                    b.HasOne("Ubrania_ASP.NET_Nowy.Models.NamesOfProperty", "NamesOfProperty")
                        .WithMany("Colors")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ubrania_ASP.NET_Nowy.Models.Mark", b =>
                {
                    b.HasOne("Ubrania_ASP.NET_Nowy.Models.NamesOfProperty", "NamesOfProperty")
                        .WithMany("Marks")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ubrania_ASP.NET_Nowy.Models.Size", b =>
                {
                    b.HasOne("Ubrania_ASP.NET_Nowy.Models.NamesOfProperty", "NamesOfProperty")
                        .WithMany("Sizes")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ubrania_ASP.NET_Nowy.Models.Type", b =>
                {
                    b.HasOne("Ubrania_ASP.NET_Nowy.Models.NamesOfProperty", "NamesOfProperty")
                        .WithMany("Types")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
